import { version } from '../../package.json'
import window from 'global/window'
import document from 'global/document'
import * as setup from './setup'
import * as stylesheet from './utils/stylesheet.js'
import Component from './component'